services:
  database:
    image: 'postgres:16.1'
    container_name: 'papyrus-database'
    ports:
      - '5432'
    environment:
      - 'POSTGRES_DB=papyrus'
      - 'POSTGRES_USER=toth'
      - 'POSTGRES_PASSWORD=parchment'
